{
 "title": "Gitops Repo Creation Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Gitops Repo Creation Requests",
   "type": "timeseries",
   "description": "The rate of gitops repo creation requests",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(has_gitops_repo_creation_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Gitops Repo Creation",
   "type": "gauge",
   "description": "Percentage of successful gitops repo creation requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1-sum(increase(has_gitops_failed_repo_creation_total[$__range]))/sum(increase(has_gitops_repo_creation_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Gitops Repo Creation",
   "type": "gauge",
   "description": "Percentage of failed gitops repo creation requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(has_gitops_failed_repo_creation_total[$__range]))/sum(increase(has_gitops_repo_creation_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}