{
 "title": "HAS Rate Limiting Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Rate Limiting Git Operations per hour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Overall Number of Rate Limiting Git Operations per hour",
   "type": "timeseries",
   "description": "Git operations that have underlying go-github API calls.  Sum across all controllers and all tokens over an interval of 1 hr",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\"}[1h]))",
     "legendFormat": "App_GenerateNewRepository"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\"}[1h]))",
     "legendFormat": "App_DeleteRepository"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\"}[1h]))",
     "legendFormat": "CDQ_GetDefaultBranchFromURL"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\",operation=\"GetBranchFromURL\"}[1h]))",
     "legendFormat": "CDQ_GetBranchFromURL"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\"}[1h]))",
     "legendFormat": "Comp_GetDefaultBranchFromURL"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\"}[1h]))",
     "legendFormat": "Comp_GetBranchFromURL"
    }
   ]
  },
  {
   "title": "Rate Limiting Git Operations per token per hour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token1",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token1\"}[1h])) by (operation) ",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token2",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token3",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token3\"}[1h])) by (operation) ",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\",operation=\"GetDefaultBranchFromURL\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token4",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token4\"}[1h])) by (operation) ",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\",operation=\"GetDefaultBranchFromURL\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token5",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token6",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token7",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token8",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token9",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token10",
     "type": "timeseries",
     "description": "Approximate Primary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate Limiting Git Operations per token per 5min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token1",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\",operation=\"GetDefaultBranchFromURL\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token2",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token3",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\",operation=\"DeleteRepository\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token4",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token5",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token6",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\",operation=\"GetBranchFromURL\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\",operation=\"GetBranchFromURL\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token7",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\",operation=\"GetBranchFromURL\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\",operation=\"GetBranchFromURL\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token8",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token9",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    },
    {
     "title": "Token10",
     "type": "timeseries",
     "description": "Approximate Secondary Rate Limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Application\", operation=\"GenerateNewRepository\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "App_GenerateNewRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{ontroller=\"Application\", operation=\"DeleteRepository\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "App_DeleteRepository"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "CDQ_GetBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetDefaultBranchFromURL\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetDefaultBranchFromURL"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetBranchFromURL\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetBranchFromURL"
      }
     ]
    }
   ]
  },
  {
   "title": "Token Pool Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token Pool Availability over an hour",
     "type": "timeseries",
     "description": "Availability of tokens in the token pool over the course of an hour.  Describes availability based on whether the tokens have been cordoned off due to  near primary rate limiting or secondary rate limitng",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\"}[1h]))",
       "legendFormat": "primary_rate_limited"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\"}[1h]))",
       "legendFormat": "secondary_rate_limited"
      }
     ]
    },
    {
     "title": "Available Tokens - Not Near Primary Rate Limited",
     "type": "gauge",
     "description": "The number of tokens left in the token pool over the course of an hour.  When token clients hit  API thresholds of core < 10 and search < 2, we cordon off the client from use",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "10-sum(increase(token_pool_gauge{rateLimited=\"primary\"}[1h]))",
       "legendFormat": "Available Tokens"
      }
     ]
    },
    {
     "title": "Available Tokens - Not Secondary Rate Limited",
     "type": "gauge",
     "description": "The number of tokens left in the token pool over 5m",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "10-sum(increase(token_pool_gauge{rateLimited=\"secondary\"}[5m]))",
       "legendFormat": "Available Tokens"
      }
     ]
    },
    {
     "title": "Cordoned Tokens  - Near Primary Rate Limited",
     "type": "timeseries",
     "description": "Tokens that have been cordoned off for use over the course of an hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token1\"}[1h])) by (tokenName)",
       "legendFormat": "token1"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token2\"}[1h])) by (tokenName)",
       "legendFormat": "token2"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token3\"}[1h])) by (tokenName)",
       "legendFormat": "token3"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token4\"}[1h])) by (tokenName)",
       "legendFormat": "token4"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token5\"}[1h])) by (tokenName)",
       "legendFormat": "token5"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token6\"}[1h])) by (tokenName)",
       "legendFormat": "token6"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token7\"}[1h])) by (tokenName)",
       "legendFormat": "token7"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token8\"}[1h])) by (tokenName)",
       "legendFormat": "token8"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token9\"}[1h])) by (tokenName)",
       "legendFormat": "token9"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"primary\",tokenName=\"token10\"}[1h])) by (tokenName)",
       "legendFormat": "token10"
      }
     ]
    },
    {
     "title": "Cordoned Tokens - Secondary Rate Limited",
     "type": "timeseries",
     "description": "Token clients that have been secondary rate limited  over 5m intervals.  These are clients that have been cordoned off from use and may or may not have hit the 403 error.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token1\"}[5m])) by (tokenName)",
       "legendFormat": "token1"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token2\"}[5m])) by (tokenName)",
       "legendFormat": "token2"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token3\"}[5m])) by (tokenName)",
       "legendFormat": "token3"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token4\"}[5m])) by (tokenName)",
       "legendFormat": "token4"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token5\"}[5m])) by (tokenName)",
       "legendFormat": "token5"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token6\"}[5m])) by (tokenName)",
       "legendFormat": "token6"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token7\"}[5m])) by (tokenName)",
       "legendFormat": "token7"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token8\"}[5m])) by (tokenName)",
       "legendFormat": "token8"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token9\"}[5m])) by (tokenName)",
       "legendFormat": "token9"
      },
      {
       "expr": "sum(increase(token_pool_gauge{rateLimited=\"secondary\",tokenName=\"token10\"}[5m])) by (tokenName)",
       "legendFormat": "token10"
      }
     ]
    }
   ]
  },
  {
   "title": "Primary Rate Limited Tokens by Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application - GenerateNewRepository",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 API rate limit exceeded error for GenerateNewRepository",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(primary_rate_limit_total{controller=\"Application\", operation=\"GenerateNewRepository\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "Application - DeleteRepository",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 API rate limit exceeded error for DeleteRepository",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(primary_rate_limit_total{controller=\"Application\", operation=\"DeleteRepository\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "CDQ - GetDefaultBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 API rate limit exceeded error for GetDefaultBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(primary_rate_limit_total{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "CDQ - GetBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 API rate limit exceeded error for GetBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(primary_rate_limit_total{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "Component - GetDefaultBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 API rate limit exceeded error for GetDefaultBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(primary_rate_limit_total{controller=\"Component\", operation=\"GetDefaultBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "CDQ - GetBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 API rate limit exceeded error for GetBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(primary_rate_limit_total{controller=\"Component\", operation=\"GetBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Secondary Rate Limited Tokens by Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application - GenerateNewRepository",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 secondary rate limit error for GenerateNewRepository",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(secondary_rate_limit_total{controller=\"Application\", operation=\"GenerateNewRepository\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "Application - DeleteRepository",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 secondary rate limit error for DeleteRepository",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(secondary_rate_limit_total{controller=\"Application\", operation=\"DeleteRepository\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "CDQ - GetDefaultBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 secondary rate limit error for GetDefaultBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(secondary_rate_limit_total{controller=\"ComponentDetectionQuery\", operation=\"GetDefaultBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "CDQ - GetBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 secondary rate limit error for GetBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(secondary_rate_limit_total{controller=\"ComponentDetectionQuery\", operation=\"GetBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "Component - GetDefaultBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 secondary rate limit error for GetDefaultBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(secondary_rate_limit_total{controller=\"Component\", operation=\"GetDefaultBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    },
    {
     "title": "Component - GetBranchFromURL",
     "type": "timeseries",
     "description": "Tokens that have hit the 403 secondary rate limit error for GetBranchFromURL",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(secondary_rate_limit_total{controller=\"Component\", operation=\"GetBranchFromURL\"}[1h])) by (tokenName) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall Git CLI Operations per hour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Overall Git CLI Operations per hour",
   "type": "timeseries",
   "description": "The number of Git CLI operations across all controllers and tokens per hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\"}[1h]))",
     "legendFormat": "Comp_GetCommitIDFromRepo"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\"}[1h]))",
     "legendFormat": "Comp_CloneGenerateAndPush"
    },
    {
     "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\"}[1h]))",
     "legendFormat": "Comp_CommitAndPush"
    }
   ]
  },
  {
   "title": "Git CLI Operations per token per hour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token1",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token1\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token2",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": " sum(increase(controller_git_request{controller=\"Component\",operation=\"CommitAndPush\", tokenName=\"token2\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token3",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token3\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token4",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token4\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token5",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token5\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token6",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token6\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token7",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token7\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token8",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "Component_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token8\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token9",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token9\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token10",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per hour",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token10\"}[1h])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    }
   ]
  },
  {
   "title": "Git CLI Operations per token per 5m",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token1",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token1\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token2",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token2\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token3",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "Component_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token3\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token4",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token4\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token5",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token5\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token6",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token6\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token7",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token7\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token8",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token8\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token9",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token9\"}[5m])) by (operation)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    },
    {
     "title": "Token10",
     "type": "timeseries",
     "description": "Non Rate limiting Git Operations per 5m",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"GetCommitIDFromRepo\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "Comp_GetCommitIDFromRepo"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CloneGenerateAndPush\", tokenName=\"token10\"}[5m])) by (operation)",
       "legendFormat": "Comp_CloneGenerateAndPush"
      },
      {
       "expr": "sum(increase(controller_git_request{controller=\"Component\", operation=\"CommitAndPush\", tokenName=\"token10\"}[5m])) by (oepration)",
       "legendFormat": "Comp_CommitAndPush"
      }
     ]
    }
   ]
  }
 ]
}