# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-viewer-role
  labels:
      rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications/status
  verbs:
  - get
