# permissions for end users to view pushes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: push-viewer-role
  labels:
      rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes/status
  verbs:
  - get
