resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

# Aggegating roles which are otherwise done by OLM
- hasapplication_editor_role.yaml
- hasapplication_viewer_role.yaml
- hascomponent_editor_role.yaml
- hascomponent_viewer_role.yaml
- haspush_editor_role.yaml
- haspush_viewer_role.yaml
- hasservicedetectionquery_editor_role.yaml
- hasservicedetectionquery_viewer_role.yaml

# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
