
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role-appsnapshot
rules:
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - appstudio.redhat.com
  resources:
    - applicationsnapshots
