# Adds namespace to all resources.
namespace: application-service-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: application-service-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
- ../manager
- ../kcp-rbac

patches:
# Disable webhooks by default on KCP
# Webhooks can be optionally enabled after deploy
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENABLE_WEBHOOKS
        value: "false"
  target:
    kind: Deployment
    name: controller-manager

# HAS on KCP needs to pass in the APIExport for HAS when the operator starts up
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --api-export-name
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: has
  target:
    kind: Deployment
    name: controller-manager