apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-to-push-cdq-image
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "main" && "cdq-analysis/***".pathChanged()
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/cdq-analysis:{{revision}}"
    - name: path-context
      value: "cdq-analysis"
    - name: infra-deployment-update-script
      value: |
        sed -i -e 's|\(https://github.com/redhat-appstudio/application-service/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/has/cdq-analysis/kustomization.yaml  
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
