apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: component-sample
  namespace: default
spec:
  componentName: sample-component-name
  application: application-sample
  source:
    git:
      url: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
  build:
    containerImage: docker.io/<your-account>/foobar:dev-code-with-quarkus
